### ISSUE TITLE
List with bullet points doesn't work

### ISSUE THREAD

**Issue by francasix** [rexxars/react-markdown#116]
I try to display a two levels list of items with bullet points but the markdown format with dash, plus or star doesn't work.

**Comment by rexxars** [comment]
Not sure what you mean?

Try pasting the following
```
- Foo
- Bar
  * Baz
    + Nope?
  * Hai?
```

Into http://rexxars.github.io/react-markdown/

Seems to work just fine for me?

**Comment by mfarzan80** [comment]
```
<Markdown
          >
            {'- Foo\n- Bar'}
          </Markdown>
   ```
          
          it show:
          
          Foo
          Bar
          
          don't show the “•”

**Comment by ChristianMurphy** [comment]
@mfarzan80 this issue is 7 years old and several major versions outdated.
You are seeing something different.
Most likely you are using tailwind css which breaks list styling.
For example https://github.com/remarkjs/react-markdown/issues/806

If you have follow up questions, feel free to start a discussion with more context.
https://github.com/orgs/remarkjs/discussions/new?category=q-a
