### ISSUE TITLE
Adding a bit of math

### ISSUE THREAD

**Issue by Cerbal** [rexxars/react-markdown#163]
This is thing called Katex which allows to interpret LaTeX and render equations beautifully. 
I notice that there is a Katex react component: https://github.com/talyssonoc/react-katex

GitLab and other tools allow to add equation between $ signs. What would be a good starting point for me to start implement this?

**Comment by ibrahima** [comment]
I've had some success simply calling [katex's autorender](https://github.com/Khan/KaTeX/tree/master/contrib/auto-render) on top of a ReactMarkdown component. However, this approach is finicky because if the Markdown parsing breaks the LaTeX syntax (eg. if there are multiple asterisks that are interpreted as italics), this will break. It's also a little scary because it's using modifying the DOM after React has done its thing, but I think it's fine as long as you do it after React has rendered so that nothing changes under you.

It seems like the right approach would be to augment the parser to detect delimited math blocks and then spit out a new node type, and have a renderer that renders the math using KaTeX. However, this may not be that simple. I'd settle for a way to tell the parser to ignore anything between delimeters that I specify, because then at least I can layer KaTeX on top without worrying about bad interactions. Not sure if that's any easier to do yet either.

**Comment by ibrahima** [comment]
Oh hey, I just realized that someone has already figured this out: https://github.com/rexxars/react-markdown/issues/10#issuecomment-347763068
