### ISSUE TITLE
Show me how to fix inline HTML

### ISSUE THREAD

**Issue by atav32** [rexxars/react-markdown#194]
Alright, I'll bite: https://github.com/rexxars/react-markdown#inline-html-is-broken. I've read through this too, https://github.com/rexxars/react-markdown/issues/43.

What's the plan?

**Comment by rexxars** [comment]
As I mentioned in #43, my main concerns are about bloating the size of the module, since we'll (most likely) have to pull in an HTML parser. One possibility is to only enable this feature for those who want it, by having a separate file/plugin you could import, say `import Markdown from 'react-markdown/withHTML'` or similar.

I don't want this component to become one of the many components that simply use innerHTML, so I'd want to use something like https://github.com/remarkablemark/html-react-parser or https://github.com/wrakky/react-html-parser to parse the HTML nodes into proper React elements.

Looking at the source now, I don't think this should be _too_ hard to do anymore (funny how I've put this off for so long), as I have many of the building blocks in place. There is a [naive html](https://github.com/rexxars/react-markdown/blob/master/src/plugins/naive-html.js) plugin I built that is enabled by default (if html rendering is on), which does a simple check for tags such as `<em>` (tags without any attributes), find the matching closing tag (if not self-closing) and generates a `virtualhtml` node. This is just a construct I made up in order to allow the simplest of tags to actually be picked up, but it could easily scale. I'd probably start by skipping _blocks_ of HTML (render those as they are done now) and just parse inline nodes with an HTML parser such as [htmlparser2](https://github.com/fb55/htmlparser2), then create an `attributes` object on `virtualhtml` nodes.

**Comment by rexxars** [comment]
@atav32 Are you still interested in working on this, or should I take a stab?

**Comment by atav32** [comment]
You'll definitely do a better job. I was just going to do it if nobody else was.

**Comment by jclif** [comment]
Would just like to second the awesomeness of this feature. We're trying to support nofollow links within our markdown sections, and this would fascilitate that quite nicely.

**Comment by QuicheSama** [comment]
I'm with @jclif, very much looking forward to this 😄

**Comment by adueck** [comment]
@atav32 looks like you might need to be the one to jump on this. We would love it if someone would do this 👍

**Comment by atav32** [comment]
Sure, let's break some eggs.

@rexxars can you point me to the relevant files I should edit. It sounds like I need to add a `withHTML` HOC? Where would you like that to live in the directory? Or should I add it as a plugin?

Are there any tests for this? If not, I'll write them.

**Comment by rexxars** [comment]
I've got a working version in #225 - sorry this took so long, and sorry I didn't see your last question. I want to see if I can fix some other API changes before I roll this out.

**Comment by rexxars** [comment]
About to roll out 4.0 with proper HTML support, so closing this.

**Comment by ekilah** [comment]
I wasn't sure whether to ask this on #225 or maybe here, so I'll just have a go at it here: after the 4.0 update, do simple (attributeless) inline HTML tags also require the new, heavy plugin now? or can they still be parsed w/o? (for example, `<sup>test</sup>`)

**Comment by rexxars** [comment]
@ekilah Without the new parse-html plugin, attributeless inline HTML tags are still parsed with the "lightweight" approach, and blocks of HTML are just dumped in using `dangerouslySetInnerHTML`.

**Comment by ekilah** [comment]
great, not sure if the new documentation covers that or not but good to know!
