### ISSUE TITLE
Dependency bloat

### ISSUE THREAD

**Issue by SimonSchick** [rexxars/react-markdown#252]
Some of your downstream dependencies seem to have poor dependency management, you might want to look into this as this makes your package rather large.

```
Duplicate dependency domelementtype installed 3 times 1.2.1,1.1.3,1.3.0!
     1.2.1: react-markdown > html-to-react > domhandler
     1.1.3: react-markdown > html-to-react > htmlparser2 > domutils > dom-serializer
     1.2.1: react-markdown > html-to-react > htmlparser2 > domutils
     1.3.0: react-markdown > html-to-react > htmlparser2
Duplicate dependency unist-util-visit-parents installed 2 times 1.1.2,2.0.1!
     1.1.2: react-markdown > mdast-add-list-metadata
     2.0.1: react-markdown > unist-util-visit
```

**Comment by rexxars** [comment]
I usually advocate for not using the HTML parsing part at all since it adds a significant weight to your bundle. By default, html-to-react will not end up in your bundle.

If this is important to you, I would suggest filing PRs to the downstream dependencies upgrading their dependencies to a common/latest target - as far as I can tell there isn't a lot I can do about this?

**Comment by SimonSchick** [comment]
In our case it turned out that we didn't actually use the package at all, it was just installed, so this isn't really an issue us anymore.

As a library author in general you should always try to keep an eye on your dependencies as bloat makes your library much less appealing.

Feel free to close this issue if you like.
