### ISSUE TITLE
Webpack build "require is not defined"

### ISSUE THREAD

**Issue by bjudson** [rexxars/react-markdown#280]
Sorry if this is the wrong place to post this, but I'm having an issue with including this library in a project being bundled by Webpack for browser usage. The build completes without error, but on opening the app I get this error:

![image](https://user-images.githubusercontent.com/542813/53748670-69dc9f80-3e6b-11e9-8931-9b64e47c2cd2.png)

I assume I can fix this with some adjustment to the Webpack config, but I'm having trouble figuring out what exactly I need to change. It seems like `vfile` is assuming a node environment?

**Comment by bjudson** [comment]
This was a webpack config issue in another project that is building my app (it's a plugin in a webview). The builder was adding `path` to Webpack externals, and it took me a bit to track that down. Got the author to fix it & now all is working.

**Comment by stivaugoin** [comment]
@bjudson I have the same issue and i'm curious to know what the author did to fix the problem. Any hint for me?
Thanks!

**Comment by khou22** [comment]
> @bjudson I have the same issue and i'm curious to know what the author did to fix the problem. Any hint for me? Thanks!

I'm also having a similar issue! Really curious to see how you fixed this. @stivaugoin did you have any luck?

**Comment by ChristianMurphy** [comment]
This issue is several years outdated, new major releases of both `react-markdown` and `webpack` have come out since, this is no longer a good source of info.
Feel free to open a discussion with your question https://github.com/orgs/remarkjs/discussions, and when opening the discussion please consider the support recommendations https://github.com/remarkjs/.github/blob/main/support.md and document which versions of webpack/react-markdown you are using so others can offer more concrete advise.
