### ISSUE TITLE
how to add custom style to codes

### ISSUE THREAD

**Issue by sayjeyhi** [rexxars/react-markdown#354]
I want to know how to add custom style to code blocks , like `max-height`.
there is closed issue with no content : #328

**Comment by jcousins-ynap** [comment]
I would use the `renderers` prop and pass it an object with `{ code: MyCustomCodeComponent }`. In `MyCustomCodeComponent` I would apply my styles.

**Comment by pupudu** [comment]
@sayjeyhi If it's not syntax highlighting that you want, plain styles can be added to code blocks easily using css. 
The markdown code block should be suffixed with the language. This will add the language- class name to the code block. And then you can use that class name to add styles. 

For example,
Write the markdown like this (Please ignore the `.` at the end.)

```
```php
$myVar = 123;
```.
```
Then it the code block will have a class name as language-php.

If you want syntax highlighting, try something like prismjs or code-mirror

**Comment by sayjeyhi** [comment]
@jcousins-ynap  @pupudu, thanks to your comment, actually I want to add `overflow-y: auto;` to large codes and make them scrollable.

**Comment by pupudu** [comment]
@sayjeyhi So yeah, then you can add a suffix to the code block 

    ```php
    $myVar = 123;
    ```
and use the resultant class name to add the styles.
```css
.language-php {
  overflow-y: auto;
}
```

Instead of `php` you can use any string. For example, you could replace it with `australia`, and then the added class name will be `language-australia`. It doesn't matter because we don't use it to do syntax highlighting
