### ISSUE TITLE
<ReactMarkdown /> when rendered, has whitespace below where its rendered

### ISSUE THREAD

**Issue by maniach1998** [rexxars/react-markdown#456]
<img width="568" alt="Screen Shot 2020-08-19 at 2 12 51 PM" src="https://user-images.githubusercontent.com/37453043/90612729-13614d80-e226-11ea-9838-e993ded08a87.png">

Creates whitespace below the rendered component. How do I fix this?

**Comment by paulkuhle** [comment]
It's because `react-markdown` converts your text blocks to paragraphs (`<p></p>` HTML tags). They have a bottom margin by default ([MDN demo](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/p)). If you want to disable the margin just for the last element of your `react-markdown` block, you can create a CSS class like this one:

```css
.markdown p:last-child {
   margin-bottom: 0;
}
```

Then wrap your `ReactMarkdown` component in a div with that class.

```javascript
<div className="markdown">
  <ReactMarkdown
    source={mySource}
  />
</div>
```
