### ISSUE TITLE
Markdown adds a <p> tag when adding quote

### ISSUE THREAD

**Issue by Marcsimm** [rexxars/react-markdown#49]
Hi. We use react-markdown and then renderer prop to map the renderer types to our own components. We have quote component that renders a paragraf where the quote is and a cite tag.

but when i look a the browser markdown adds paragraf inside paragraf so they get nested  
  
```
<blockquote class="block-quote__blockquote">
  <p class="block-quote__quote">
    <p class="running-text__RunningText">
    <!-- react-text: 578 -->“I have faced rejection so many times that I’ve lost track of how many times. Every time you’re asking someone to buy your product, you’re really asking them to embrace change…”<!-- /react-text -->
    </p>
  </p>
</blockquote>
```
can i prevent it from doing that?

**Comment by rexxars** [comment]
Sorry for not responding earlier, I've been a bit busy with life. 

I need some more info to understand this. How does your markdown source look, and what are you renderers doing?

**Comment by Marcsimm** [comment]
Sorry for the delay. So in the renderer we render our own components instead of letting react-markdown doing it. Paragrah for example is rendered as a RunningText component and quote as BlockQuote component as seen above. But when the renderer looks at a quote it wraps the text with the RunningText component (associated to paragraph) and then with the BlockQuote component, instead of having the text as a direct child of the BlockQuote component.

**Comment by adrianvalenz** [comment]
I guess he is still busy with life.

**Comment by rexxars** [comment]
Kind of forgot about this one.

The reason why this happens is because a blockquote can contain lots of things, not just text. Lists, sub-quotes and the like. It basically works the same way that text at the root of a markdown document works - it'll be wrapped in a paragraph.

You can see the AST for a markdown document by using [this tool](http://spec.commonmark.org/dingus/) and click "AST" on the right. You could unwrap the children of your paragraph if you need to, using [React.Children](https://facebook.github.io/react/docs/react-api.html#react.children) and the like.
