### ISSUE TITLE
Limiting features available

### ISSUE THREAD

**Issue by bobiblazeski** [rexxars/react-markdown#5]
Is it possible to limit the advanced markdown features.
I would like to have only below markdown

Emphasis
===============
*This text will be italic*

**This text will be bold**

Lists
===============
Unordered

* Item 1
* Item 2
  * Item 2a
  * Item 2b

Ordered

1. Item 1
2. Item 2
3. Item 3
  * Item 3a
  * Item 3b

**Comment by rexxars** [comment]
Not currently, but this seems like a great idea. I'll see if I can get the time to work on this soon.

**Comment by rexxars** [comment]
Implemented in `1.1.0` that was just released. 

In your case:
```
<Markdown
  source={someMarkdownString}
  allowedTypes={['Text', 'Paragraph', 'List', 'Item', 'Emph', 'Strong']}
/>
```

Possibly also want to allow `Softbreak` and `Hardbreak`. See the readme for available types.

**Comment by bobiblazeski** [comment]
Many thanks

**Comment by Ogglas** [comment]
@rexxars 

If we want `react-markdown` to only render **bold** and _italic_ in version `7.1.2` would this be the best option then?

```
<ReactMarkdown children={`${props.text}`} allowedElements={["strong", "em"]} unwrapDisallowed={true} />
```

This works good but if a user want's to write `>` they have to write it as `\>` otherwise the character will be removed. If `blockquote` in this example is not allowed it would be nice if the `>` character was whitelisted. 

https://commonmark.org/help/

**Comment by ChristianMurphy** [comment]
@Ogglas potentially, depending on how you want to handle the rest of the markdown constructs.
If you have follow up question, `react-markdown` uses discussions (https://github.com/remarkjs/remark/discussions) for Q&A, rather than issues, happy to help more there.
