### ISSUE TITLE
<br/> doesn't work

### ISSUE THREAD

**Issue by sebmor** [rexxars/react-markdown#6]
When typing 2 strings, and putting each on a new line using Enter. Instead of rendering a BR it will render each in a separate span (including empty span)

<img width="576" alt="screen shot 2015-11-25 at 03 38 07" src="https://cloud.githubusercontent.com/assets/405407/11386896/13a526d0-9326-11e5-84bc-c65f9249ddcb.png">

<img width="379" alt="screen shot 2015-11-25 at 03 38 37" src="https://cloud.githubusercontent.com/assets/405407/11386898/14b7fee4-9326-11e5-9e9d-4e321a7fdad7.png">

**Comment by sebmor** [comment]
Discovered softBreak="br". That works.

Does it make "Softbreak" and "Hardbreak" in allowedTypes obsolete?

**Comment by rexxars** [comment]
Hi and thanks for the report,

No, a soft break is usually treated as just a hint, while a hardbreak is always treated as an explicit linebreak. A hardbreak can be achieved by having two or more spaces at the end of a line, followed by a newline character. This is according to the markdown "standard".

The softbreak option is included because many people find the default behavior of newlines confusing, and depending on what you are building, this might make more sense in your case.
