### ISSUE TITLE
Errors with npm install and Running

### ISSUE THREAD

**Issue by jshuadvd** [rexxars/react-markdown#9]
Hi there. I have tried several times to get the development version working to no avail. Here is a screen shot of my terminal:
![screen shot 2015-12-12 at 6 59 23 pm](https://cloud.githubusercontent.com/assets/7577457/11765219/b7933e46-a102-11e5-893d-bef84fa115ec.png)

I have done everything I can think of. The demo will not load at all. I have successfully installed via npm in my project and I can get the markdown rendered to the page, but nothing else. The documentation is unclear on how to get this to look like the demo page as well as how to start the demo. I tried the webpack command, npm start everything.  I even created a directory and tried to run gulp to see if I could fix it, but no there also. Can you provide me an explanation as to what I am doing wrong?

**Comment by rexxars** [comment]
Things move quickly in the javascript world. I've done a few changes now that ensures that the prepublish step is not run on install. I've also made sure that the projects builds with the correct and latest versions of babel, and I've fixed an issue that was causing webpack not to output correct bundles.

Can you please give it another shot?

I'm not sure what exactly you are trying to do - the demo is runnable by serving the `demo/dist` folder through a webserver (`npm install -g node-static && static demo/dist`, for instance). If you want to make changes to the demo, you can run the watch task at the same time: `npm run watch`.

The primary use case isn't a side-by-side editor/preview thing, which is why I have not given much thought to how the demo should be run or the quality of the codemirror integration that's currently running there.

**Comment by rexxars** [comment]
Closing this since I have not heard back. Let me know if I can help further.

**Comment by jshuadvd** [comment]
Apologies for the delay as I didn't realize you responded. I will try the new method that you mentioned and let you know my results. 

As for what I am trying to do is to simply get this running and be able to test the demo and see how everything was working. I could not accomplish that with the current instructions that are provided on the read me. 

I understand that the demo is not your primary concern, but it does help me for the use case and wanted to see how everything worked in a live setting even though I can read the code and determine what is happening. Thanks for your prompt response. If you don't mind , please keep this open so that I may respond with my results. I hope all is well.
